{
"photo":"https://s3.amazonaws.com/coursera/topics/algs4partII/large-icon.png",
"preview_link":null,
"small_icon_hover":"https://s3.amazonaws.com/coursera/topics/algs4partII/small-icon.hover.png",
"large_icon":"https://s3.amazonaws.com/coursera/topics/algs4partII/large-icon.png",
"video":"GO8frjxq25I",
"university-ids":["princeton"],
"id":27,
"universities":[{"rectangular_logo_svg":"","wordmark":null,"website_twitter":"princeton","favicon":"https://coursera-university-assets.s3.amazonaws.com/d4/29daf4b768e1aa467202d4d2dcf8d8/favicon-princeton.ico","website_facebook":"PrincetonU","logo":"https://coursera-university-assets.s3.amazonaws.com/94/cc9200e336d38ce029873b13cbe93b/logo-princeton-front.png","background_color":"","id":4,"location_city":"","location_country":"","location_lat":null,"location":"","primary_color":"#BA632D","abbr_name":"Princeton","website":"http://www.princeton.edu/","description":"Princeton University is a private research university located in Princeton, New Jersey, United States. It is one of the eight universities of the Ivy League, and one of the nine Colonial Colleges founded before the American Revolution.","short_name":"princeton","landing_page_banner":"https://coursera-university-assets.s3.amazonaws.com/88/84ac58eed29633d7a951928ad9aa17/banner1.jpg","mailing_list_id":null,"website_youtube":"princetonuniversity/","banner":"https://coursera-university-assets.s3.amazonaws.com/b9/4cbcc8b5a797cdaff8a944cc55b22f/banner-princeton.jpg","location_state":"","name":"Princeton University","square_logo":"https://coursera-university-assets.s3.amazonaws.com/44/8de6f8bd5ac4cf7e36bdcf7ceff393/PU_subscription_logo.png","square_logo_source":"https://coursera-university-assets.s3.amazonaws.com/63/480dbb489b5e6570ebffb8304c3053/PU_subscription_logo.png","square_logo_svg":"","location_lng":null,"home_link":null,"class_logo":"https://coursera-university-assets.s3.amazonaws.com/0f/c062f1496dedaf429cdf6c5c8ed471/PUsig2.png","display":true}],
"small_icon":"https://s3.amazonaws.com/coursera/topics/algs4partII/small-icon.hover.png",
"self_service_course_id":null,
"short_description":"This course covers the essential information that every serious programmer needs to know about algorithms and data structures, with emphasis on applications and scientific performance analysis of Java implementations.",
"short_name":"algs4partII",
"category-ids":["cs-theory","cs-programming"],
"visibility":0,
"social_link":"https://www.coursera.org/course/algs4partII",
"instructor":"Kevin Wayne and Robert Sedgewick",
"categories":[{"id":1,"name":"Computer Science: Theory","mailing_list_id":null,"short_name":"cs-theory","description":"Our wide range of courses allows students to explore topics from many different fields of study. Sign up for a class today and join our global community of students and scholars!"},{"id":12,"name":"Computer Science: Software Engineering","mailing_list_id":null,"short_name":"cs-programming","description":"Our wide range of courses allows students to explore topics from many different fields of study. Sign up for a class today and join our global community of students and scholars!"}],
"name":"Algorithms, Part II",
"language":"en",
"courses":[{"grading_policy_distinction":"","ace_track_price_display":null,"signature_track_certificate_design_id":null,"ace_semester_hours  ":null,"start_day":25,"duration_string":"7 weeks","signature_track_last_chance_time":null,"id":970478,"start_month":3,"certificate_description":"","start_date_string":null,"eligible_for_ACE":null,"signature_track_regular_price":null,"grades_release_date":null,"certificates_ready":false,"signature_track_price":null,"statement_design_id":null,"topic_id":27,"eligible_for_signature_track":false,"start_date":null,"status":1,"start_year":2013,"end_date":null,"instructors":[246867,250165],"active":true,"eligible_for_certificates":false,"deployed":true,"ace_close_date":null,"name":"002","signature_track_open_time":null,"grading_policy_normal":"","ace_open_date":null,"home_link":"https://class.coursera.org/algs4partII-001/","creator_id":63735,"proctored_exam_completion_date":null,"university_logo":null,"signature_track_close_time":null}],
"university_logo":"",
"course-ids":[970478],
"display":true
},


small_icon
short_name
name
social_link
short_description
instructor
universities->name
universities->website
universities->short_name (coursera.org/short_name)
courses->start_day
courses->start_month
courses->start_year
courses->duration_string
courses->start_date_string

list of universities: https://www.coursera.org/maestro/api/university/list 
list of all courses:  https://www.coursera.org/maestro/api/topic/list?full=1
course description: https://www.coursera.org/maestro/api/topic/information?topic-id=nutrition




{'photo': 'https://s3.amazonaws.com/coursera/topics/ml/large-icon.png',
'preview_link': 'https://class.coursera.org/ml/lecture/preview',
'small_icon_hover': 'https://s3.amazonaws.com/coursera/topics/ml/small-icon.hover.png',
'large_icon': 'https://s3.amazonaws.com/coursera/topics/ml/large-icon.png',
'video': 'e0WKJLovaZg',
'university-ids': ['stanford'],
'id': 2,
'universities': [{'rectangular_logo_svg': None,
		'wordmark': None,
		'website_twitter': '',
		'favicon': 'https://coursera-university-assets.s3.amazonaws.com/dc/581cda352d067023dcdcc0d9efd36e/favicon-stanford.ico',
		'website_facebook': '',
		'id': 1,
		'logo': 'https://coursera-university-assets.s3.amazonaws.com/d8/4c69670e0826e42c6cd80b4a02b9a2/stanford.png',
		'background_color': '',
		'mailing_list_id': None,
		'location_city': 'Palo Alto',
		'location_country': 'US',
		'location_lat': 37.4418834,
		'location': 'Palo Alto,
		CA,
		United States',
		'primary_color': '#8c1515',
		'abbr_name': 'Stanford',
		'website': '',
		'description': 'The Leland Stanford Junior University,
		commonly referred to as Stanford University or Stanford,
		is an American private research university located in Stanford,
		California on an 8,180-acre (3,310 ha) campus near Palo Alto,
		California,
		United States.',
		'short_name': 'stanford',
		'location_state': 'CA',
		'website_youtube': '',
		'banner': '',
		'landing_page_banner': '',
		'name': 'Stanford University',
		'square_logo': '',
		'square_logo_source': None,
		'display': True,
		'location_lng': -122.14301949999998,
		'home_link': 'http://online.stanford.edu/',
		'class_logo': 'https://coursera-university-assets.s3.amazonaws.com/21/9a0294e2bf773901afbfcb5ef47d97/Stanford_Coursera-200x48_RedText_BG.png',
		'square_logo_svg': None}],
'small_icon': 'https://s3.amazonaws.com/coursera/topics/ml/small-icon.hover.png',
'self_service_course_id': None,
'short_description': 'Learn about the most effective machine learning techniques,
and gain practice implementing them and getting them to work for yourself.',
'short_name': 'ml',
'category-ids': ['stats','cs-ai'],
'visibility': 0,
'social_link': 'https://www.coursera.org/course/ml',
'instructor': 'Andrew Ng,
Associate Professor',
'categories': [{'mailing_list_id': None,
	      'description': 'Our wide range of courses allows students to explore topics from many different fields of study. Sign up for a class today and join our global community of students and scholars!',
	      'id': 16,
	      'short_name': 'stats',
	      'name': 'Statistics and Data Analysis'},
	      {'mailing_list_id': None,
	      'description': 'Our wide range of courses allows students to explore topics from many different fields of study. Sign up for a class today and join our global community of students and scholars!',
	      'id': 17,
	      'short_name': 'cs-ai',
	      'name': 'Computer Science: Artificial Intelligence'}],
'name': 'Machine Learning',
'language': 'en',
'courses': [{'grading_policy_distinction': 'N/A',
	   'ace_track_price_display': None,
	   'signature_track_certificate_design_id': None,
	   'ace_semester_hours': None,
	   'start_year': 2012,
	   'duration_string': '10 weeks',
	   'signature_track_last_chance_time': None,
	   'id': 16,
	   'start_month': 4,
	   'certificate_description': 'This course provided a broad introduction to machine learning,
	   datamining,
	   and statistical pattern recognition. Course content included several methods in supervised learning and unsupervised learning,
	   illustrated through case studies and applications.',
	   'start_date_string': '23 April 2012',
	   'eligible_for_ACE': False,
	   'signature_track_regular_price': None,
	   'grades_release_date': '2012-12-06',
	   'creator_id': None,
	   'signature_track_price': None,
	   'statement_design_id': 8,
	   'topic_id': 2,
	   'eligible_for_signature_track': False,
	   'start_date': None,
	   'status': 0,
	   'start_day': 23,
	   'end_date': None,
	   'instructors': [232841],
	   'active': True,
	   'eligible_for_certificates': True,
	   'deployed': True,
	   'ace_close_date': None,
	   'name': '12-001',
	   'signature_track_open_time': None,
	   'grading_policy_normal': 'The final grade was based on 18 equally-weighted quizzes (1/3 of the total grade) and 8 programming assignments (2/3 of the total grade).  To receive a Statement of Accomplishment,
	   you must have obtained 80% or more of the maximum possible score.',
	   'ace_open_date': None,
	   'home_link': 'https://class.coursera.org/ml/',
	   'certificates_ready': True,
	   'proctored_exam_completion_date': None,
	   'university_logo': '',
	   'signature_track_close_time': None},
	   {'grading_policy_distinction': 'N/A',
	   'ace_track_price_display': None,
	   'signature_track_certificate_design_id': None,
	   'ace_semester_hours': None,
	   'start_year': 2012,
	   'duration_string': '10 weeks',
	   'signature_track_last_chance_time': None,
	   'id': 152,
	   'start_month': 8,
	   'certificate_description': 'Congratulations! You have successfully completed the online Machine Learning course (ml-class.org). To successfully complete the course,
	   students were required to watch lectures,
	   review questions and complete programming assignments. ',
	   'start_date_string': '20 August 2012',
	   'eligible_for_ACE': False,
	   'signature_track_regular_price': None,
	   'grades_release_date': '2013-03-10',
	   'creator_id': None,
	   'signature_track_price': None,
	   'statement_design_id': 8,
	   'topic_id': 2,
	   'eligible_for_signature_track': False,
	   'start_date': None,
	   'status': 0,
	   'start_day': 20,
	   'end_date': None,
	   'instructors': [232841],
	   'active': True,
	   'eligible_for_certificates': True,
	   'deployed': True,
	   'ace_close_date': None,
	   'name': '12-002',
	   'signature_track_open_time': None,
	   'grading_policy_normal': 'The final grade was based on 18 equally-weighted quizzes (1/3 of the total grade) and 8 programming assignments (2/3 of the total grade).  The lowest two quiz grades were dropped,
	   as well as the lowest programming assignment grade. To receive a Statement of Accomplishment,
	   you must have obtained 80% or more of the maximum possible score.',
	   'ace_open_date': None,
	   'home_link': 'https://class.coursera.org/ml-2012-002/',
	   'certificates_ready': True,
	   'proctored_exam_completion_date': None,
	   'university_logo': '',
	   'signature_track_close_time': None},
	   {'grading_policy_distinction': '',
	   'ace_track_price_display': None,
	   'signature_track_certificate_design_id': None,
	   'ace_semester_hours': None,
	   'start_year': 2013,
	   'duration_string': '10 weeks',
	   'signature_track_last_chance_time': None,
	   'id': 970311,
	   'start_month': 4,
	   'certificate_description': '',
	   'start_date_string': None,
	   'eligible_for_ACE': False,
	   'signature_track_regular_price': None,
	   'grades_release_date': None,
	   'creator_id': None,
	   'signature_track_price': None,
	   'statement_design_id': None,
	   'topic_id': 2,
	   'eligible_for_signature_track': False,
	   'start_date': None,
	   'status': 1,
	   'start_day': 22,
	   'end_date': None,
	   'instructors': [1244],
	   'active': False,
	   'eligible_for_certificates': True,
	   'deployed': True,
	   'ace_close_date': None,
	   'name': '003',
	   'signature_track_open_time': None,
	   'grading_policy_normal': '',
	   'ace_open_date': None,
	   'home_link': 'https://class.coursera.org/ml-003/',
	   'certificates_ready': False,
	   'proctored_exam_completion_date': None,
	   'university_logo': None,
	   'signature_track_close_time': None}],
'university_logo': '',
'course-ids': [16,
152,
970311],
'display': True}


{u'photo': u'https://coursera-course-photos.s3.amazonaws.com/91/ae57afe43398e0152daf8b550731af/GuineaPigsHeroesPatients_Logo.jpg', u'preview_link': None, u'small_icon_hover': u'https://coursera-course-photos.s3.amazonaws.com/39/8c435446f27af68b1b7ad531e692ca/GuineaPigsHeroesPatients_Logo.jpg', u'large_icon': u'https://coursera-course-photos.s3.amazonaws.com/e3/b656f1c64eb69615dc1af6e6e0641d/GuineaPigsHeroesPatients_Logo.jpg', u'video': u'', u'university-ids': [u'jhu'], u'id': 526, u'universities': [{u'rectangular_logo_svg': None, u'wordmark': None, u'website_twitter': u'JohnsHopkins', u'favicon': u'https://coursera-university-assets.s3.amazonaws.com/80/d81353ccd0bab30962a5770d7aec97/favicon-jhu.ico', u'website_facebook': u'johnshopkinsuniversity', u'id': 8, u'logo': u'https://coursera-university-assets.s3.amazonaws.com/cf/0db65d1501244b9e6eacfa5e637fea/logo-jhu-front.png', u'background_color': u'', u'mailing_list_id': None, u'location_city': u'Baltimore', u'location_country': u'US', u'location_lat': 39.2903848, u'location': u'Baltimore, MD', u'primary_color': u'#0061AA', u'abbr_name': u'Johns Hopkins', u'website': u'http://www.jhu.edu/', u'description': u'The mission of The Johns Hopkins University is to educate its students and cultivate their capacity for life-long learning, to foster independent and original research, and to bring the benefits of discovery to the world.', u'short_name': u'jhu', u'location_state': u'MD', u'website_youtube': u'johnshopkins', u'banner': u'https://coursera-university-assets.s3.amazonaws.com/83/94437b11dcbef874ea1f30d960a26b/banner-jhu.jpg', u'landing_page_banner': u'https://coursera-university-assets.s3.amazonaws.com/c2/544537cee93c0acd67b6573d46a32e/Coursera-banner.jpg', u'name': u'Johns Hopkins University', u'square_logo': u'https://coursera-university-assets.s3.amazonaws.com/f6/4798f308d4eaa66fc53e99a92d65e5/JHU_360x360.png', u'square_logo_source': u'https://coursera-university-assets.s3.amazonaws.com/39/7f8dfbe935fe6b3f1eb2e85e307375/JHU_360x360.png', u'display': True, u'location_lng': -76.61218930000001, u'home_link': None, u'class_logo': u'', u'square_logo_svg': u''}], u'small_icon': u'https://coursera-course-photos.s3.amazonaws.com/39/8c435446f27af68b1b7ad531e692ca/GuineaPigsHeroesPatients_Logo.jpg', u'self_service_course_id': None, u'short_description': u'Learn about the ethical issues that arise when conducting human subjects research, as well as the history that grounds policies and debates in this area of biomedicine.', u'short_name': u'humanresearch', u'category-ids': [u'medicine', u'humanities', u'biology', u'socsci'], u'visibility': 0, u'social_link': None, u'instructor': u'Jeffrey Kahn, Alan C Regenberg and Debra JH Mathews', u'categories': [{u'mailing_list_id': None, u'description': u'Our wide range of courses allows students to explore topics from many different fields of study. Sign up for a class today and join our global community of students and scholars!', u'id': 3, u'short_name': u'medicine', u'name': u'Medicine'}, {u'mailing_list_id': 11, u'description': u'Our wide range of courses allows students to explore topics from many different fields of study. Sign up for a class today and join our global community of students and scholars!', u'id': 6, u'short_name': u'humanities', u'name': u'Humanities '}, {u'mailing_list_id': None, u'description': u'Our wide range of courses allows students to explore topics from many different fields of study. Sign up for a class today and join our global community of students and scholars!', u'id': 10, u'short_name': u'biology', u'name': u'Biology & Life Sciences'}, {u'mailing_list_id': None, u'description': u'', u'id': 20, u'short_name': u'socsci', u'name': u'Social Sciences'}], u'name': u'Guinea Pigs, Heroes & Desperate Patients: The History & Ethics of Human Research', u'language': u'en', u'courses': [{u'grading_policy_distinction': u'', u'ace_track_price_display': None, u'signature_track_certificate_design_id': None, u'ace_semester_hours': None, u'start_year': None, u'duration_string': u'', u'signature_track_last_chance_time': None, u'id': 970828, u'start_month': None, u'certificate_description': u'', u'start_date_string': None, u'eligible_for_ACE': False, u'signature_track_regular_price': None, u'grades_release_date': None, u'creator_id': 2083331, u'signature_track_price': None, u'statement_design_id': None, u'topic_id': 526, u'eligible_for_signature_track': False, u'start_date': None, u'status': 1, u'start_day': None, u'end_date': None, u'instructors': [1164831, 2075104, 2083331], u'active': False, u'eligible_for_certificates': True, u'deployed': True, u'ace_close_date': None, u'name': u'001', u'signature_track_open_time': None, u'grading_policy_normal': u'', u'ace_open_date': None, u'home_link': u'https://class.coursera.org/humanresearch-001/', u'certificates_ready': False, u'proctored_exam_completion_date': None, u'university_logo': None, u'signature_track_close_time': None}], u'university_logo': u'', u'course-ids': [970828], u'display': True}
2013-03-31 21:18:40+1000 [coursera] DEBUG: item: {'coursedate': 'TBA',
